### ISSUE TITLE
Record on route53 is not being created.

### ISSUE THREAD

**Issue by NorfairKing** [NixOS/nixops-aws#115]
I have this record define in my resources:

```
      cs-syd-mx = { resources, ... }: {
        inherit accessKeyId;
        zoneId = resources.route53HostedZones.cs-syd-zone;
        domainName = "cs-syd.eu.";
        ttl = 14400;
        recordValues = [
          "10 in1-smtp.messagingengine.com."
          "20 in2-smtp.messagingengine.com."
        ];
        recordType = "MX";
      };
```

Looking at the aws console, the record clearly *does not* exist.

![mx](https://user-images.githubusercontent.com/3521180/94659791-195a4c00-0305-11eb-83f9-19f4289cc61a.png)

However, `nixops check` shows it as fine:

```
Non machines resources state:
+---------------------------+--------+
| Name                      | Exists |
+---------------------------+--------+
| cs-syd-mx                 | Yes    |
+---------------------------+--------+
```

And `nixops deploy` does not create it.

**Comment by NorfairKing** [comment]
Workaround: Slightly change the recordValues, deploy, change it back, deploy again.

**Comment by NorfairKing** [comment]
I just noticed that the same thing happened for a TXT record so I'm guessing it's got nothing to do with the record type.

**Comment by tewfik-ghariani** [comment]
Can you show a bit more of the nix expression? It is working fine for me, here is my example

```
   resources.route53RecordSets.server-dns =
    { config, resources, lib, ... }:
    {
      accessKeyId = account;
      zoneName = "example.com";
      name = dnsName;
      domainName = "${dnsName}.";
      routingPolicy = "simple";
      recordType = "A";
      recordValues = [ resources.machines.machine ];
    };
```

**Comment by NorfairKing** [comment]
@tewfik-ghariani I now have a dns checker: https://github.com/NorfairKing/dnscheck so this won't be a big problem for me anymore.
If you cannot reproduce this problem, there's nothing else I can do at this point I'm afraid..

**Comment by tewfik-ghariani** [comment]
@NorfairKing The reason why I asked you to share more of the nix expressions but I am having some doubts that the resource type itself is not being set correct. What this means is that the `cs-syd-mx` should be preceded by the **route53RecordSets** resource type. 
Otherwise, it is just considered as a machine on its own.

Not sure though if this is the root cause of the issue you described

**Comment by NorfairKing** [comment]
@tewfik-ghariani Here you go:

```
  resources = {
    # Some things omitted here
    route53RecordSets = {
      # Some things omitted here
      # Fastmail settings
      cs-syd-mx = { resources, ... }: {
        inherit accessKeyId;
        zoneId = resources.route53HostedZones.cs-syd-zone;
        domainName = "cs-syd.eu.";
        ttl = 14400;
        recordValues = [
          "10 in1-smtp.messagingengine.com."
          "20 in2-smtp.messagingengine.com."
        ];
        recordType = "MX";
      };
      # Some things omitted here
```

**Comment by tewfik-ghariani** [comment]
I just spun up a deployment with your code and I didn't see any issue

```
$ nixops deploy -d route53-record
cs-syd-zone> creating hosted zone for cs-syd.eu
cs-syd-mx..> creating/updating record set (MX/cs-syd.eu.)
building all machine configurations...
route53-record> closures copied successfully
route53-record> deployment finished successfully
```
```
+-------------+--------+-------------------------+-----------------------------------+------------+
| Name        | Status | Type                    | Resource Id                       | IP address |
+-------------+--------+-------------------------+-----------------------------------+------------+
| cs-syd-zone |   Up   | aws-route53-hosted-zone | /hostedzone/Z08481123SD4EZQBHZW6J |            |
| cs-syd-mx   |   Up   | aws-route53-recordset   | cs-syd.eu.                        |            |
+-------------+--------+-------------------------+-----------------------------------+------------+

```
The MX records can be found in the AWS console

![image](https://user-images.githubusercontent.com/11073604/104515800-8fa06700-55f3-11eb-9de3-2740b9b8327a.png)

**Comment by NorfairKing** [comment]
> I just spun up a deployment with your code and I didn't see any issue

Yes I also didn't see any issue the first time around, but at some point the record both didn't exist _and_ wasn't being created _and_ `check` didn't mention anything.
This smells like a state problem, which really shouldn't be an issue that exists with `nixops`.

**Comment by tewfik-ghariani** [comment]
@NorfairKing  my best guess is that the hosted zone was manually deleted from AWS Console/API. You could look through the cloudtrail logs but it'll take a while

I believe the real problem here is that the `check` method is not defined for both 'route53-hosted-zone' and 'route53-recordset' resources. Which mean that there is no API call to actually **check** the state of these resources.

The re-creation didn't happen as well because for the state file, the resources already exist. Perhaps a solution would be to run a `deploy` operation with the `--check` option.

**Comment by NorfairKing** [comment]
> I believe the real problem here is that the check method is not defined for both 'route53-hosted-zone' and 'route53-recordset' resources. Which mean that there is no API call to actually check the state of these resources.

I guess this is the real issue then, right?

**Comment by tewfik-ghariani** [comment]
@NorfairKing  I just tested that specific scenario and deploying with `--check` option does solve the issue indeed

```
$ nixops deploy -d route53-record --check
cs-syd-mx..> creating/updating record set (MX/cs-syd.eu.)
building all machine configurations...
route53-record> closures copied successfully
route53-record> deployment finished successfully
```

I manually deleted the record set and running simple `deploy` or `check` couldn't detect that. Using the `check` flag was all what's needed to re-create the route53-recordset resource

**Comment by NorfairKing** [comment]
Huh, good to know! Should we close this issue?

**Comment by tewfik-ghariani** [comment]
If the answer is what you're looking for then yeah I guess, as you like ^^

**Comment by NorfairKing** [comment]
This just happened again. The DNS record mysteriously dissappeared, `nixops deploy` didn't put it back, but `nixops deploy --check` did.
What does `nixops deploy --check` do differently and why isn't it the default?

**Comment by tewfik-ghariani** [comment]
@NorfairKing  It might be worth it to take a look at the *CloudTrail* logs and check if there has been any recent "Delete Route53 Resources" calls

In this case, the `--check` flag allows the **create** ( deploy ) operation to continue either creating/updating the record-set regardless of its current state. If it was not specified, the operation would just stop there since, for the state file, the record-set still supposedly exists and no parameters were changed in the "defn" by the user

Ref : https://github.com/NixOS/nixops-aws/blob/ce9e0ae63981c5c727a688eec5c314e38694eba2/nixops_aws/resources/route53_recordset.py#L256-L261

**Comment by NorfairKing** [comment]
@tewfik-ghariani Shouldn't `nixops deploy` guarantee that the real state corresponds to the specified state, independently of what is currently wrong? So if someone goes and mucks about in the console manually, `nixops deploy` would put that back?
It seems to me that `--check` should be the default then?

I'm thoroughly surprised that this is how `nixops deploy` works. Is there any downside to just always deploying with `--check`?

**Comment by tewfik-ghariani** [comment]
@NorfairKing I believe that the `deploy` command does not re-verify the state of resources by design. Perhaps the nixops maintainers know better about the initial design decisions related to drift detection

In any case, one of the best practices is to periodically run a `check` command before deploying to reflect the actual states of all resources. So I guess what's missing here is the route53 record-set own `check` method to update its status from AWS 

Any thoughts @AmineChikhaoui ?
